# Generated by Django 4.2.7 on 2023-11-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='was edited'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='is removed'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['submit_date'], name='comments_co_submit__2c7423_idx'),
        ),
    ]
