# Generated by Django 4.2.7 on 2023-11-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('can_moderate', 'Can moderate comments')], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=3000, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False, help_text='Check this box if the comment is inappropriate. A "This comment has been removed" message will be displayed instead.', verbose_name='is removed'),
        ),
    ]
