# Generated by Django 4.2.3 on 2023-10-10 12:51

import django.db.models.deletion
from django.db import migrations, models

import news.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsSite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.CharField(max_length=200)),
                ("rss_url", models.CharField(blank=True, max_length=200, null=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField(blank=True, null=True)),
                ("url", models.CharField(max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("subtitle", models.CharField(blank=True, max_length=200, null=True)),
                ("author", models.CharField(default="Anonymous", max_length=200)),
                (
                    "pub_date",
                    models.DateTimeField(validators=[news.models.validate_not_future], verbose_name="date published"),
                ),
                ("image_url", models.CharField(blank=True, max_length=400, null=True)),
                ("image_caption", models.CharField(blank=True, max_length=200, null=True)),
                ("news_site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="news.newssite")),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
    ]
