# Generated by Django 4.2.3 on 2023-07-19 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submissiondownvote",
            name="submission",
        ),
        migrations.RemoveField(
            model_name="submissiondownvote",
            name="user",
        ),
        migrations.RemoveField(
            model_name="submissionupvote",
            name="submission",
        ),
        migrations.RemoveField(
            model_name="submissionupvote",
            name="user",
        ),
        migrations.DeleteModel(
            name="Submission",
        ),
        migrations.DeleteModel(
            name="SubmissionDownvote",
        ),
        migrations.DeleteModel(
            name="SubmissionUpvote",
        ),
    ]
