# Generated by Django 5.0 on 2023-12-09 19:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('url', models.URLField(blank=True, max_length=255, verbose_name='url')),
                ('body', models.CharField(blank=True, max_length=10000, verbose_name='body')),
                ('html', models.TextField(blank=True, null=True, verbose_name='html')),
                ('image_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='image alt')),
                ('submit_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date submitted')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
