# Generated by Django 5.0 on 2023-12-07 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='image alt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='submit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date submitted'),
        ),
    ]
