# Generated by Django 5.0 on 2023-12-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_image_alt_alter_post_submit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html',
            field=models.TextField(blank=True, verbose_name='html'),
        ),
    ]
