# Generated by Django 4.2.3 on 2023-07-07 23:49

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models

import newsapp.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsSite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=200)),
                ("rss_url", models.CharField(max_length=200)),
                ("logo", models.ImageField(blank=True, upload_to="logos/")),
            ],
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("author", models.CharField(default="Anonymous", max_length=200)),
                (
                    "pub_date",
                    models.DateTimeField(
                        validators=[newsapp.models.validate_not_future], verbose_name="date published"
                    ),
                ),
                ("text", models.TextField()),
                ("image_url", models.CharField(blank=True, max_length=400)),
                ("image_caption", models.CharField(blank=True, max_length=200)),
                ("url", models.CharField(max_length=200)),
                ("news_site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="newsapp.newssite")),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("votes", models.IntegerField(default=0)),
                ("pub_date", models.DateTimeField(auto_now_add=True, verbose_name="date published")),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "news_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="newsapp.newsitem"
                    ),
                ),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="newsapp.comment",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
