# Generated by Django 4.2.3 on 2023-07-05 00:43

import django.db.models.deletion
from django.db import migrations, models

import newsapp.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsSite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=200)),
                ("rss_url", models.CharField(max_length=200)),
                ("logo", models.ImageField(blank=True, upload_to="logos/")),
            ],
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("author", models.CharField(default="Anonymous", max_length=200)),
                (
                    "pub_date",
                    models.DateTimeField(
                        validators=[newsapp.models.validate_not_future], verbose_name="date published"
                    ),
                ),
                ("content", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="images/%Y/%m/%d/")),
                ("image_caption", models.CharField(blank=True, max_length=200)),
                ("url", models.CharField(max_length=200)),
                ("news_site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="newsapp.newssite")),
            ],
        ),
    ]
