# Generated by Django 4.2.3 on 2023-07-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="flagged",
            field=models.BooleanField(default=False),
        ),
    ]
