# Generated by Django 4.2.3 on 2023-07-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="deleted_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="edited_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
