# Generated by Django 4.2.3 on 2023-07-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsapp", "0002_comment_flagged"),
    ]

    operations = [
        migrations.AddField(
            model_name="newssite",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
