# Generated by Django 4.2.3 on 2023-07-08 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("newsapp", "0002_comment_deleted_on_comment_edited_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="pub_date",
            new_name="created_on",
        ),
        migrations.AddField(
            model_name="comment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deleted_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edited_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
