# Generated by Django 4.2.3 on 2023-07-06 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("newsapp", "0002_remove_newsitem_image_newsitem_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsitem",
            old_name="content",
            new_name="text_content",
        ),
        migrations.AddField(
            model_name="newsitem",
            name="comment_count",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text_content", models.TextField()),
                ("pub_date", models.DateTimeField(auto_now_add=True, verbose_name="date published")),
                ("news_item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="newsapp.newsitem")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="newsapp.comment"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
