# Generated by Django 4.2.3 on 2023-07-14 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newsapp", "0003_newssite_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="votes",
        ),
    ]
