# Generated by Django 4.2.3 on 2023-07-14 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newsapp", "0004_remove_post_votes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="value",
        ),
    ]
